package identcode3131

import (
	"bytes"
	"fmt"

	identcode "github.com/nangantata/go-identcode"
	"github.com/nangantata/go-identcode/internal"
)

// IdentCodeB62Len is the length of ident code text generated by PackB62, excluding the prefix.
const IdentCodeB62Len = internal.Uint32Base62EncodedLen + internal.Uint32Base62EncodedLen

// PackB62 packages the given identValue and generated randomKey into identCodeText using Base62 encoding.
// A randomKey is generated and used to select a mask from identMasks to mask the identValue.
// The masked identValue and the randomKey are then encoded into the identCodeText.
func PackB62(prefixText string, identMasks *[16]uint32, identValue int32) (identCodeText string, randomKey int32) {
	randomKey = internal.GenerateNonZeroRandomKey31()
	prefixBytes := []byte(prefixText)
	prefixLen := len(prefixBytes)
	resultBuf := make([]byte, prefixLen, prefixLen+internal.Uint32Base62EncodedLen+internal.Uint32Base62EncodedLen)
	copy(resultBuf, prefixBytes)
	maskedIdentValue := uint32(identValue) ^ (*identMasks)[int(randomKey&0xF)]
	resultBuf = internal.Base62AppendEncodeUint32(resultBuf, maskedIdentValue)
	resultBuf = internal.Base62AppendEncodeUint32(resultBuf, uint32(randomKey))
	identCodeText = string(resultBuf)
	return
}

// UnpackB62 unpacks the given identCodeText to retrieve the original identValue and randomKey.
func UnpackB62(prefixText string, identMasks *[16]uint32, identCodeText string) (identValue int32, randomKey int32, err error) {
	prefixBytes := []byte(prefixText)
	identCodeBytes := []byte(identCodeText)
	if !bytes.HasPrefix(identCodeBytes, prefixBytes) {
		err = identcode.ErrPrefixNotMatch
		return
	}
	prefixLen := len(prefixBytes)
	if (len(identCodeBytes) - prefixLen) != (internal.Uint32Base62EncodedLen + internal.Uint32Base62EncodedLen) {
		err = identcode.ErrEncodedLengthNotMatch
		return
	}
	maskedIdentValue, err := internal.Base62DecodeUint32(identCodeBytes[prefixLen:])
	if err != nil {
		err = fmt.Errorf("cannot decode ident value: %w", err)
		return
	}
	rawRandomKey, err := internal.Base62DecodeUint32(identCodeBytes[prefixLen+internal.Uint32Base62EncodedLen:])
	if err != nil {
		err = fmt.Errorf("cannot decode random key: %w", err)
		return
	}
	identValue = int32(maskedIdentValue ^ (*identMasks)[int(rawRandomKey&0xF)])
	randomKey = int32(rawRandomKey)
	return
}
